Repository knative-extensions/sample-source, pull requests merged in 2020-09, with the labels that each got.

#154 [master] Update GitHub Actions
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-stale.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: approved, cla: yes, lgtm, size/M

#155 [master] Update GitHub Actions
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: approved, cla: yes, lgtm, size/S

#156 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#157 Add linting config and fix issues.
  .golangci.yaml
  pkg/adapter/adapter_test.go
  pkg/reconciler/sample/controller.go
  pkg/reconciler/sinkbinding.go
Labels: approved, cla: yes, lgtm, size/S

#158 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/metrics/config_observability.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#159 [master] Update GitHub Actions
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/S

#160 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/adapter/v2/main.go
  vendor/knative.dev/eventing/pkg/apis/configs/v1alpha1/configmappropagation_validation.go
  vendor/knative.dev/eventing/pkg/apis/flows/v1/parallel_defaults.go
  vendor/knative.dev/eventing/pkg/apis/flows/v1/sequence_defaults.go
  vendor/knative.dev/eventing/pkg/apis/flows/v1beta1/parallel_defaults.go
  vendor/knative.dev/eventing/pkg/apis/flows/v1beta1/sequence_defaults.go
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/reconciler/retry.go
  vendor/knative.dev/pkg/webhook/configmaps/configmaps.go
  vendor/knative.dev/test-infra/scripts/README.md
  vendor/knative.dev/test-infra/scripts/e2e-tests.sh
  vendor/knative.dev/test-infra/scripts/infra-library.sh
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/knative.dev/test-infra/scripts/presubmit-tests.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#162 [master] Update GitHub Actions
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/M

#163 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/adapter/v2/main.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#164 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/test-infra/scripts/e2e-tests.sh
  vendor/knative.dev/test-infra/scripts/infra-library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#165 enable code coverage
  .codecov.yaml
  .github/workflows/knative-go-test.yaml
Labels: approved, cla: yes, lgtm, size/S

#168 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#169 Add lease cluster role to the controller and webhook
  config/201-clusterrole.yaml
  config/203-webhook-clusterrole.yaml
Labels: approved, cla: yes, lgtm, size/S

#170 [master] Update GitHub Actions
  .github/workflows/knative-donotsubmit.yaml
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: approved, cla: yes, lgtm, size/L

#172 [master] Update GitHub Actions
  .github/workflows/knative-boilerplate.yaml
Labels: approved, cla: yes, lgtm, size/M

#173 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/adapter/v2/config.go
  vendor/knative.dev/eventing/pkg/adapter/v2/config_watcher.go
  vendor/knative.dev/eventing/pkg/adapter/v2/context.go
  vendor/knative.dev/eventing/pkg/adapter/v2/main.go
  vendor/knative.dev/eventing/pkg/adapter/v2/main_message.go
  vendor/knative.dev/eventing/pkg/leaderelection/context.go
  vendor/knative.dev/eventing/pkg/leaderelection/leader_election.go
  vendor/knative.dev/eventing/pkg/utils/cache/persisted_store.go
  vendor/knative.dev/pkg/metrics/resource_view.go
  vendor/knative.dev/pkg/network/transports.go
  vendor/knative.dev/pkg/webhook/stats_reporter.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XL

#175 [Automated] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/packages.go
  vendor/knative.dev/pkg/kmeta/names.go
  vendor/knative.dev/pkg/metrics/config.go
  vendor/knative.dev/pkg/metrics/exporter.go
  vendor/knative.dev/pkg/metrics/opencensus_exporter.go
  vendor/knative.dev/pkg/webhook/conversion.go
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#176 [Automated] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/adapter/v2/cloudevents.go
  vendor/knative.dev/eventing/pkg/apis/duck/v1/fuzzer.go
  vendor/knative.dev/eventing/pkg/apis/duck/v1beta1/subscribable_types_conversion.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha2/container_validation.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1beta1/container_validation.go
  vendor/knative.dev/eventing/pkg/tracing/setup.go
  vendor/knative.dev/pkg/apis/condition_set.go
  vendor/knative.dev/pkg/apis/duck/v1/destination.go
  vendor/knative.dev/pkg/apis/duck/v1/status_types.go
  vendor/knative.dev/pkg/apis/duck/v1beta1/status_types.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/logging/config.go
  vendor/knative.dev/pkg/logging/logkey/constants.go
  vendor/knative.dev/pkg/metrics/config.go
  vendor/knative.dev/pkg/metrics/stackdriver_exporter.go
  vendor/knative.dev/pkg/reconciler/events.go
  vendor/knative.dev/pkg/tracing/config/tracing.go
  vendor/knative.dev/test-infra/scripts/infra-library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#177 [Automated] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#178 [Automated] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/kncloudevents/message_sender.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#179 [Automated] Update actions
  .github/workflows/knative-verify.yaml
Labels: approved, cla: yes, lgtm, size/XS

#182 [Automated] Update actions
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: approved, cla: yes, lgtm, size/M

#181 [Automated] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/kncloudevents/message_sender.go
  vendor/knative.dev/pkg/metrics/metrics.go
  vendor/knative.dev/pkg/metrics/workqueue.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#183 [Automated] Update actions
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/M

#184 [Automated] Upgrade to latest dependencies
  go.mod
  go.sum
  pkg/client/injection/reconciler/samples/v1alpha1/samplesource/controller.go
  pkg/client/injection/reconciler/samples/v1alpha1/samplesource/reconciler.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/packages.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_controller.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#185 [Automated] Update actions
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/XS

#186 [Automated] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/client.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/duck.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/factory.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/fakeclient.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/fakeduck.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/fakefactory.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/fakeinformer.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/informer.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_controller.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_controller_stub.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler_stub.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_state.go
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/metrics/stackdriver_exporter.go
  vendor/knative.dev/pkg/profiling/server.go
  vendor/knative.dev/pkg/webhook/admission.go
  vendor/knative.dev/pkg/webhook/certificates/certificates.go
  vendor/knative.dev/pkg/webhook/configmaps/configmaps.go
  vendor/knative.dev/pkg/webhook/conversion.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/defaulting/defaulting.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/validation/validation_admit.go
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M
