Repository knative-extensions/sample-source, pull requests merged in 2020-05, with the labels that each got.

#72 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/tracing/attributes.go
  vendor/knative.dev/pkg/metrics/metricskey/constants.go
  vendor/knative.dev/pkg/metrics/utils.go
  vendor/knative.dev/pkg/network/transports.go
  vendor/knative.dev/pkg/source/source_stats_reporter.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#77 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/flows/v1alpha1/parallel_types.go
  vendor/knative.dev/eventing/pkg/apis/flows/v1alpha1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/apis/flows/v1beta1/parallel_types.go
  vendor/knative.dev/eventing/pkg/apis/flows/v1beta1/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/apis/duck/v1/kresource_type.go
  vendor/knative.dev/pkg/configmap/parse.go
  vendor/knative.dev/pkg/metrics/config.go
  vendor/knative.dev/pkg/reconciler/reconcile_common.go
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/knative.dev/test-infra/scripts/shellcheck-presubmit.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#79 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta1/broker_types.go
  vendor/knative.dev/pkg/metrics/config.go
  vendor/knative.dev/pkg/network/network.go
  vendor/knative.dev/pkg/webhook/env.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#78 Fix wrong refs to event type
  config/300-samplesource.yaml
  pkg/apis/samples/v1alpha1/samplesource_types.go
Labels: approved, cla: yes, lgtm, size/XS

#80 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/configmap/parse.go
  vendor/knative.dev/pkg/leaderelection/config.go
  vendor/knative.dev/pkg/metrics/config_observability.go
  vendor/knative.dev/pkg/tracing/config/tracing.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#82 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/gopkg.in/yaml.v2/apic.go
  vendor/knative.dev/pkg/hack/update-deps.sh
  vendor/knative.dev/pkg/reconciler/reconcile_common.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#83 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/config/defaults.go
  vendor/knative.dev/eventing/pkg/apis/messaging/config/channel_defaults.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1alpha1/channel_conversion.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1alpha1/in_memory_channel_conversion.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#84 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/messaging/v1alpha1/in_memory_channel_defaults.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1beta1/in_memory_channel_defaults.go
  vendor/knative.dev/test-infra/scripts/update-test-infra.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#85 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta1/broker_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta1/broker_types.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta1/eventtype_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta1/eventtype_types.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta1/trigger_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta1/trigger_types.go
  vendor/knative.dev/pkg/apis/duck/v1/status_types.go
  vendor/knative.dev/pkg/apis/duck/v1/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/apis/duck/v1beta1/status_types.go
  vendor/knative.dev/pkg/apis/duck/v1beta1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#86 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/configmap/store.go
  vendor/knative.dev/pkg/logging/config
  vendor/knative.dev/pkg/logging/object_encoders.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#87 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/eventing/v1alpha1/broker_conversion.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1alpha1/eventtype_types.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta1/eventtype_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta1/eventtype_types.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta1/register.go
  vendor/knative.dev/pkg/apis/duck/v1/status_types.go
  vendor/knative.dev/pkg/apis/duck/v1beta1/status_types.go
  vendor/knative.dev/pkg/hack/update-deps.sh
  vendor/knative.dev/pkg/kmeta/map.go
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#88 update to use cloudevents sdk v2.0.0
  go.mod
  go.sum
  vendor/github.com/cloudevents/sdk-go/v2/alias.go
  vendor/github.com/cloudevents/sdk-go/v2/client/client.go
  vendor/github.com/cloudevents/sdk-go/v2/event/event_marshal.go
  vendor/github.com/cloudevents/sdk-go/v2/go.mod
  vendor/github.com/cloudevents/sdk-go/v2/go.sum
  vendor/github.com/cloudevents/sdk-go/v2/protocol/http/abuse_protection.go
  vendor/github.com/cloudevents/sdk-go/v2/protocol/http/options.go
  vendor/github.com/cloudevents/sdk-go/v2/protocol/http/protocol.go
  vendor/github.com/cloudevents/sdk-go/v2/protocol/http/result.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XL

#89 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/eventing/register.go
  vendor/knative.dev/pkg/apis/duck/v1/status_types.go
  vendor/knative.dev/pkg/apis/duck/v1beta1/status_types.go
  vendor/knative.dev/pkg/configmap/parse.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M
