Repository knative-extensions/sample-source, pull requests merged in 2020-04, with the labels that each got.

#47 [master] Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/test-infra/scripts/presubmit-tests.sh
Labels: approved, cla: yes, lgtm, size/S

#48 [master] Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/eventing/pkg/apis/flows/v1beta1/test_helpers.go
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/apis/condition_set.go
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/metrics/config.go
  vendor/knative.dev/pkg/metrics/config_observability.go
  vendor/knative.dev/pkg/metrics/exporter.go
  vendor/knative.dev/pkg/testutils/clustermanager/e2e-tests/config.go
  vendor/knative.dev/pkg/testutils/clustermanager/e2e-tests/gke.go
  vendor/knative.dev/pkg/testutils/clustermanager/e2e-tests/util.go
  vendor/knative.dev/pkg/testutils/clustermanager/prow-cluster-operation/actions/create.go
  vendor/knative.dev/pkg/testutils/clustermanager/prow-cluster-operation/actions/delete.go
  vendor/knative.dev/pkg/testutils/metahelper/client/client.go
  vendor/knative.dev/pkg/testutils/metahelper/main.go
Labels: approved, cla: yes, lgtm, size/L

#49 [master] Auto-update dependencies
  Gopkg.lock
  vendor/github.com/go-logr/logr/LICENSE
  vendor/github.com/go-logr/logr/logr.go
  vendor/github.com/kballard/go-shellquote/LICENSE
  vendor/github.com/kballard/go-shellquote/doc.go
  vendor/github.com/kballard/go-shellquote/quote.go
  vendor/github.com/kballard/go-shellquote/unquote.go
  vendor/knative.dev/eventing/config/200-jobrunner-clusterrole.yaml
  vendor/knative.dev/eventing/config/201-jobrunner-serviceaccount.yaml
  vendor/knative.dev/eventing/config/brokers/mt-channel-broker/200-channel-clusterrole.yaml
  vendor/knative.dev/eventing/config/brokers/mt-channel-broker/201-channel-clusterrolebinding.yaml
  vendor/knative.dev/eventing/pkg/tracing/traceparent_transformer.go
  vendor/knative.dev/eventing/pkg/tracing/transformers.go
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/apiextensions/storageversion/cmd/migrate/config.go
  vendor/knative.dev/pkg/apiextensions/storageversion/cmd/migrate/main.go
  vendor/knative.dev/pkg/apiextensions/storageversion/migrator.go
  vendor/knative.dev/pkg/apis/contexts.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/packages.go
  vendor/knative.dev/pkg/leaderelection/config.go
  vendor/knative.dev/pkg/metrics/monitored_resources.go
  vendor/knative.dev/pkg/resolver/addressable_resolver.go
  vendor/knative.dev/pkg/test/cmd/command.go
  vendor/knative.dev/pkg/test/e2e_flags.go
  vendor/knative.dev/pkg/test/logging/sugar.go
  vendor/knative.dev/pkg/test/logging/tlogger.go
  vendor/knative.dev/pkg/test/testgrid/testgrid.go
  vendor/knative.dev/pkg/testing/resource.go
  vendor/knative.dev/pkg/testutils/clustermanager/e2e-tests/gke.go
  vendor/knative.dev/pkg/testutils/clustermanager/e2e-tests/setup.go
  vendor/knative.dev/pkg/testutils/clustermanager/e2e-tests/util.go
  vendor/knative.dev/pkg/testutils/clustermanager/prow-cluster-operation/options/options.go
  vendor/knative.dev/pkg/tracker/enqueue.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/conversion/conversion.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/validation/controller.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/validation/reconcile_config.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/validation/validation_admit.go
  vendor/knative.dev/pkg/webhook/testing/testing.go
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/knative.dev/test-infra/tools/dep-collector/gobuild.go
  vendor/knative.dev/test-infra/tools/dep-collector/imports.go
  vendor/knative.dev/test-infra/tools/dep-collector/licenses.go
Labels: approved, cla: yes, lgtm, size/XXL

#50 Preparing for v0.14 release, point pkg to release-0.14.
  Gopkg.lock
  Gopkg.toml
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/apis/duck/ABOUT.md
  vendor/knative.dev/pkg/apis/duck/images/Knative-Duck0.png
Labels: approved, cla: yes, lgtm, size/L

#51 [master] Auto-update dependencies
  Gopkg.lock
  vendor/github.com/go-logr/logr/LICENSE
  vendor/github.com/go-logr/logr/logr.go
  vendor/github.com/kballard/go-shellquote/LICENSE
  vendor/github.com/kballard/go-shellquote/doc.go
  vendor/github.com/kballard/go-shellquote/quote.go
  vendor/github.com/kballard/go-shellquote/unquote.go
  vendor/knative.dev/test-infra/tools/dep-collector/gobuild.go
Labels: approved, cla: yes, lgtm, size/XL

#57 [master] Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/Gopkg.toml
  vendor/knative.dev/test-infra/scripts/presubmit-tests.sh
Labels: approved, cla: yes, lgtm, size/S

#58 Post v0.14 release, point pkg to master.
  Gopkg.lock
  Gopkg.toml
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/Gopkg.toml
  vendor/knative.dev/pkg/OWNERS_ALIASES
  vendor/knative.dev/pkg/RELEASING.md
  vendor/knative.dev/pkg/configmap/testing/configmap.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/logging/config
  vendor/knative.dev/pkg/metrics/config_observability.go
  vendor/knative.dev/pkg/tracing/config/tracing.go
Labels: approved, cla: yes, lgtm, size/L

#59 [master] Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/pkg/DEVELOPMENT.md
  vendor/knative.dev/pkg/logging/config.go
  vendor/knative.dev/pkg/test/helpers/name.go
Labels: approved, cla: yes, lgtm, size/M

#60 [master] Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/pkg/apis/contexts.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/validation/reconcile_config.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/validation/validation_admit.go
Labels: approved, cla: yes, lgtm, size/M

#61 [master] Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/pkg/apis/duck/cached.go
Labels: approved, cla: yes, lgtm, size/M

#62 [master] Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/eventing/cmd/mtping/kodata/HEAD
  vendor/knative.dev/eventing/cmd/mtping/kodata/LICENSE
  vendor/knative.dev/eventing/cmd/mtping/kodata/VENDOR-LICENSE
  vendor/knative.dev/eventing/cmd/mtping/kodata/refs
  vendor/knative.dev/eventing/cmd/ping/adapter/kodata/HEAD
  vendor/knative.dev/eventing/cmd/ping/adapter/kodata/LICENSE
  vendor/knative.dev/eventing/cmd/ping/adapter/kodata/VENDOR-LICENSE
  vendor/knative.dev/eventing/cmd/ping/adapter/kodata/refs
  vendor/knative.dev/eventing/cmd/ping/jobrunner/kodata/HEAD
  vendor/knative.dev/eventing/cmd/ping/jobrunner/kodata/LICENSE
  vendor/knative.dev/eventing/cmd/ping/jobrunner/kodata/VENDOR-LICENSE
  vendor/knative.dev/eventing/cmd/ping/jobrunner/kodata/refs
  vendor/knative.dev/eventing/cmd/ping/kodata/HEAD
  vendor/knative.dev/eventing/cmd/ping/kodata/LICENSE
  vendor/knative.dev/eventing/cmd/ping/kodata/VENDOR-LICENSE
  vendor/knative.dev/eventing/cmd/ping/kodata/refs
  vendor/knative.dev/eventing/config/200-jobrunner-clusterrole.yaml
  vendor/knative.dev/eventing/config/200-pingsource-mt-adapter-clusterrole.yaml
  vendor/knative.dev/eventing/config/201-jobrunner-serviceaccount.yaml
  vendor/knative.dev/eventing/config/201-pingsource-mt-adapter-serviceaccount.yaml
  vendor/knative.dev/eventing/pkg/apis/duck/v1beta1/delivery_types.go
  vendor/knative.dev/test-infra/scripts/presubmit-tests.sh
Labels: approved, cla: yes, lgtm, size/M

#63 [master] Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/reconciler/testing/table.go
  vendor/knative.dev/pkg/webhook/psbinding/reconciler.go
Labels: approved, cla: yes, lgtm, size/M

#64 [master] Auto-update dependencies
  Gopkg.lock
  pkg/client/injection/reconciler/samples/v1alpha1/samplesource/controller.go
  pkg/client/injection/reconciler/samples/v1alpha1/samplesource/reconciler.go
  vendor/knative.dev/pkg/client/injection/apiextensions/reconciler/apiextensions/v1beta1/customresourcedefinition/controller.go
  vendor/knative.dev/pkg/client/injection/apiextensions/reconciler/apiextensions/v1beta1/customresourcedefinition/reconciler.go
  vendor/knative.dev/pkg/client/injection/kube/reconciler/core/v1/namespace/controller.go
  vendor/knative.dev/pkg/client/injection/kube/reconciler/core/v1/namespace/reconciler.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_controller.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/controller/options.go
  vendor/knative.dev/pkg/tracing/config/tracing.go
Labels: approved, cla: yes, lgtm, size/L

#65 [master] Auto-update dependencies
  Gopkg.lock
  pkg/client/injection/reconciler/samples/v1alpha1/samplesource/reconciler.go
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/client/injection/apiextensions/reconciler/apiextensions/v1beta1/customresourcedefinition/reconciler.go
  vendor/knative.dev/pkg/client/injection/kube/reconciler/core/v1/namespace/reconciler.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/webhook/admission.go
  vendor/knative.dev/test-infra/scripts/library.sh
Labels: approved, cla: yes, lgtm, size/M

#66 [master] Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/eventing/pkg/apis/messaging/v1alpha1/in_memory_channel_conversion.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1beta1/in_memory_channel_defaults.go
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/client/injection/apiextensions/reconciler/apiextensions/v1beta1/customresourcedefinition/reconciler.go
  vendor/knative.dev/pkg/client/injection/kube/reconciler/core/v1/namespace/reconciler.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/leaderelection/config.go
  vendor/knative.dev/pkg/reconciler/testing/tracker.go
  vendor/knative.dev/pkg/test/mako/sidecar.go
  vendor/knative.dev/pkg/test/mako/stub-sidecar/main.go
  vendor/knative.dev/pkg/test/webhook-apicoverage/resourcetree/basictypekindnode.go
  vendor/knative.dev/pkg/tracker/enqueue.go
  vendor/knative.dev/pkg/tracker/interface.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/defaulting/controller.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/validation/controller.go
  vendor/knative.dev/test-infra/scripts/presubmit-tests.sh
Labels: approved, cla: yes, lgtm, size/L

#68 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/injection/context.go
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/metrics/stackdriver_exporter.go
  vendor/knative.dev/pkg/tracing/config/tracing.go
  vendor/knative.dev/pkg/tracing/opencensus.go
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M
