Repository knative-extensions/sample-source, pull requests merged in 2020-10, with the labels that each got.

#188 [Automated] Update actions
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/XS

#190 [Automated] Update actions
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/S

#191 [Automated] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/adapter/v2/cloudevents.go
  vendor/knative.dev/eventing/pkg/adapter/v2/config.go
  vendor/knative.dev/eventing/pkg/adapter/v2/main.go
  vendor/knative.dev/eventing/pkg/apis/duck/v1/delivery_types.go
  vendor/knative.dev/eventing/pkg/apis/duck/v1beta1/delivery_types.go
  vendor/knative.dev/eventing/pkg/apis/sources/constants.go
  vendor/knative.dev/pkg/apis/field_error.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/packages.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/main.go
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/metrics/prometheus_exporter.go
  vendor/knative.dev/pkg/metrics/resource_view.go
  vendor/knative.dev/pkg/profiling/server.go
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#192 [Automated] Update actions
  .github/workflows/knative-boilerplate.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-security.yaml
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/M

#187 Use CRD & Webhook v1 api
  config/300-samplesource.yaml
  config/500-webhook-configration.yaml
Labels: approved, cla: yes, lgtm, size/M

#193 [Automated] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/apis/duck/v1/binding_types.go
  vendor/knative.dev/pkg/apis/duck/v1/register.go
  vendor/knative.dev/pkg/apis/duck/v1/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/injection/config.go
  vendor/knative.dev/pkg/injection/injection.go
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#195 [Automated] Update actions
  .github/workflows/knative-security.yaml
Labels: approved, cla: yes, lgtm, size/XS

#196 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/adapter/v2/config.go
  vendor/knative.dev/eventing/pkg/adapter/v2/main_message.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1/container_defaults.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1/container_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1/container_types.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1/container_validation.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1/register.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/sources/v1/containersource.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/sources/v1/generated_expansion.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/sources/v1/sources_client.go
  vendor/knative.dev/eventing/pkg/client/informers/externalversions/generic.go
  vendor/knative.dev/eventing/pkg/client/informers/externalversions/sources/v1/containersource.go
  vendor/knative.dev/eventing/pkg/client/informers/externalversions/sources/v1/interface.go
  vendor/knative.dev/eventing/pkg/client/listers/sources/v1/containersource.go
  vendor/knative.dev/eventing/pkg/client/listers/sources/v1/expansion_generated.go
  vendor/knative.dev/eventing/pkg/kncloudevents/message_receiver.go
  vendor/knative.dev/eventing/pkg/kncloudevents/message_sender.go
  vendor/knative.dev/eventing/pkg/kncloudevents/utils.go
  vendor/knative.dev/test-infra/scripts/release.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XL

#198 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/webhook/certificates/resources/certs.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#200 Fix release labels to be samples.knative.dev/release
  config/201-clusterrole.yaml
  config/203-webhook-clusterrole.yaml
  config/500-webhook-configration.yaml
  config/500-webhook.yaml
Labels: approved, cla: yes, lgtm, size/S

#201 Add release.sh, update deps
  go.mod
  hack/release.sh
  hack/tools.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#202 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/sources/v1/container_conversion.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha2/container_conversion.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1beta1/container_conversion.go
  vendor/knative.dev/pkg/configmap/store.go
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/metrics/config_observability.go
  vendor/knative.dev/pkg/metrics/stackdriver_exporter.go
  vendor/knative.dev/pkg/tracing/config/tracing.go
  vendor/knative.dev/pkg/tracing/setup.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#203 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/adapter/v2/config.go
  vendor/knative.dev/eventing/pkg/configmap/reader.go
  vendor/knative.dev/eventing/pkg/configmap/store.go
  vendor/knative.dev/eventing/pkg/kncloudevents/populate_span_transformer.go
  vendor/knative.dev/eventing/pkg/tracing/attributes.go
  vendor/knative.dev/eventing/pkg/tracing/names.go
  vendor/knative.dev/eventing/pkg/tracing/setup.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#204 [Automated] Update actions
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/XS

#205 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  pkg/client/injection/reconciler/samples/v1alpha1/samplesource/reconciler.go
  vendor/knative.dev/eventing/pkg/apis/config/defaults.go
  vendor/knative.dev/eventing/pkg/apis/config/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/broker_defaults.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta1/broker_defaults.go
  vendor/knative.dev/eventing/pkg/apis/messaging/register.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1/in_memory_channel_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1beta1/in_memory_channel_lifecycle.go
  vendor/knative.dev/pkg/apis/duck/README.md
  vendor/knative.dev/pkg/apis/field_error.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/controller/two_lane_queue.go
  vendor/knative.dev/pkg/hash/doc.go
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/kmeta/ownerrefable_accessor.go
  vendor/knative.dev/pkg/leaderelection/context.go
  vendor/knative.dev/pkg/logging/config.go
  vendor/knative.dev/pkg/metrics/config_observability.go
  vendor/knative.dev/pkg/metrics/exporter.go
  vendor/knative.dev/pkg/network/network.go
  vendor/knative.dev/pkg/tracing/opencensus.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/validation/controller.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/validation/validation_admit.go
  vendor/knative.dev/pkg/webhook/stats_reporter.go
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/knative.dev/test-infra/scripts/shellcheck-presubmit.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#206 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/injection/config.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#207 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/kncloudevents/utils.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#208 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/duck/v1/fuzzer.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/injection/config.go
  vendor/knative.dev/pkg/kmeta/names.go
  vendor/knative.dev/pkg/metrics/config.go
  vendor/knative.dev/pkg/reconciler/events.go
  vendor/knative.dev/pkg/tracing/config/tracing.go
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#209 [Automated] Update actions
  .github/workflows/knative-releasability.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#210 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#211 [Automated] Update actions
  .github/workflows/knative-boilerplate.yaml
  .github/workflows/knative-donotsubmit.yaml
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-security.yaml
  .github/workflows/knative-stale.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#212 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/metrics/config.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#214 [Automated] Update actions
  .github/workflows/knative-releasability.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#215 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  pkg/client/injection/reconciler/samples/v1alpha1/samplesource/reconciler.go
  vendor/k8s.io/apimachinery/pkg/api/apitesting/fuzzer/fuzzer.go
  vendor/k8s.io/apimachinery/pkg/api/apitesting/fuzzer/valuefuzz.go
  vendor/knative.dev/eventing/pkg/adapter/v2/cloudevents.go
  vendor/knative.dev/eventing/pkg/adapter/v2/config.go
  vendor/knative.dev/eventing/pkg/apis/duck/v1/fuzzer.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/fuzzer.go
  vendor/knative.dev/eventing/pkg/apis/flows/v1/fuzzer.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1/fuzzer.go
  vendor/knative.dev/eventing/pkg/reconciler/source/config_watcher.go
  vendor/knative.dev/pkg/apis/duck/v1/fuzzer.go
  vendor/knative.dev/pkg/apis/duck/v1beta1/fuzzer.go
  vendor/knative.dev/pkg/apis/testing/fuzzer/fuzzer.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/leaderelection/config.go
  vendor/knative.dev/pkg/leaderelection/context.go
  vendor/knative.dev/pkg/logging/config.go
  vendor/knative.dev/pkg/metrics/config.go
  vendor/knative.dev/pkg/resolver/addressable_resolver.go
  vendor/knative.dev/pkg/tracing/config/tracing.go
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/XL

#216 Update sinkbinding api usage to v1 (from v1alpha2)
  pkg/reconciler/resources/sink_binding.go
  pkg/reconciler/sinkbinding.go
Labels: approved, cla: yes, lgtm, size/S

#217 [Automated] Update actions
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#221 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#223 [Automated] Update actions
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/S

#222 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/apis/duck/verify.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/logging/config.go
  vendor/knative.dev/pkg/metrics/opencensus_exporter.go
  vendor/knative.dev/pkg/metrics/stackdriver_exporter.go
  vendor/knative.dev/pkg/network/transports.go
  vendor/knative.dev/pkg/reconciler/events.go
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/M
