Repository knative-extensions/sample-source, pull requests merged in 2020-03, with the labels that each got.

#16 Add an `--upgrade` flag to `./hack/update-deps.sh`
  hack/update-deps.sh
Labels: approved, lgtm, size/S

#17 vendor in cloudevents sdk.
  Gopkg.lock
  Gopkg.toml
  vendor/github.com/cloudevents/sdk-go/alias.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/client/client.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/client/defaulters.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/client/observability.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/client/options.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/datacodec/json/observability.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/datacodec/observability.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/datacodec/xml/observability.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/event.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/event_interface.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/event_marshal.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/event_observability.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/event_writer.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/eventcontext.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/eventcontext_v1.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/extensions.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/extensions/distributed_tracing_extension.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/observability/observer.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/transport/http/codec.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/transport/http/context.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/transport/http/observability.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/transport/http/options.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/transport/http/transport.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/transport/transport.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/types/value.go
  vendor/github.com/lightstep/tracecontext.go/LICENSE
  vendor/github.com/lightstep/tracecontext.go/traceparent/package.go
  vendor/github.com/lightstep/tracecontext.go/tracestate/package.go
  vendor/go.opencensus.io/plugin/ochttp/propagation/tracecontext/propagation.go
Labels: approved, lgtm, size/XXL

#19 golang format tools
  pkg/adapter/adapter.go
  pkg/apis/samples/v1alpha1/samplesource_lifecycle.go
Labels: approved, lgtm, size/XS

#20 Fix the contributing link.
  CONTRIBUTING.md
Labels: approved, lgtm, size/XS

#22 Fix the links in DEVELOPMENT.md too
  DEVELOPMENT.md
Labels: approved, lgtm, size/S

#24 Format markdown
  CONTRIBUTING.md
  DEVELOPMENT.md
Labels: approved, lgtm, size/S

#27 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/eventing/cmd/cronjob_receive_adapter/kodata/HEAD
  vendor/knative.dev/eventing/cmd/cronjob_receive_adapter/kodata/LICENSE
  vendor/knative.dev/eventing/cmd/cronjob_receive_adapter/kodata/VENDOR-LICENSE
  vendor/knative.dev/eventing/cmd/cronjob_receive_adapter/kodata/refs
  vendor/knative.dev/eventing/config/300-legacyapiserversource.yaml
  vendor/knative.dev/eventing/config/300-legacycontainersource.yaml
  vendor/knative.dev/eventing/config/300-legacycronjobsource.yaml
  vendor/knative.dev/eventing/config/300-legacysinkbinding.yaml
  vendor/knative.dev/eventing/config/500-webhook-legacysinkbindings.yaml
  vendor/knative.dev/eventing/pkg/apis/eventing/v1alpha1/test_helper.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1alpha1/trigger_conversion.go
  vendor/knative.dev/eventing/pkg/apis/legacysources/register.go
  vendor/knative.dev/eventing/pkg/apis/legacysources/v1alpha1/apiserver_defaults.go
  vendor/knative.dev/eventing/pkg/apis/legacysources/v1alpha1/apiserver_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/legacysources/v1alpha1/apiserver_types.go
  vendor/knative.dev/eventing/pkg/apis/legacysources/v1alpha1/apiserver_validation.go
  vendor/knative.dev/eventing/pkg/apis/legacysources/v1alpha1/containersource_defaults.go
  vendor/knative.dev/eventing/pkg/apis/legacysources/v1alpha1/containersource_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/legacysources/v1alpha1/containersource_types.go
  vendor/knative.dev/eventing/pkg/apis/legacysources/v1alpha1/containersource_validation.go
  vendor/knative.dev/eventing/pkg/apis/legacysources/v1alpha1/cron_job_defaults.go
  vendor/knative.dev/eventing/pkg/apis/legacysources/v1alpha1/cron_job_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/legacysources/v1alpha1/cron_job_types.go
  vendor/knative.dev/eventing/pkg/apis/legacysources/v1alpha1/cron_job_validation.go
  vendor/knative.dev/eventing/pkg/apis/legacysources/v1alpha1/deprecated.go
  vendor/knative.dev/eventing/pkg/apis/legacysources/v1alpha1/doc.go
  vendor/knative.dev/eventing/pkg/apis/legacysources/v1alpha1/register.go
  vendor/knative.dev/eventing/pkg/apis/legacysources/v1alpha1/sinkbinding_context.go
  vendor/knative.dev/eventing/pkg/apis/legacysources/v1alpha1/sinkbinding_defaults.go
  vendor/knative.dev/eventing/pkg/apis/legacysources/v1alpha1/sinkbinding_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/legacysources/v1alpha1/sinkbinding_types.go
  vendor/knative.dev/eventing/pkg/apis/legacysources/v1alpha1/sinkbinding_validation.go
  vendor/knative.dev/eventing/pkg/apis/legacysources/v1alpha1/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/injection/README.md
  vendor/knative.dev/test-infra/scripts/README.md
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/knative.dev/test-infra/scripts/markdown-link-check-config.rc
  vendor/knative.dev/test-infra/scripts/presubmit-tests.sh
Labels: approved, lgtm, size/XXL

#28 Use ko's strict mode for better errors messages
  config/500-controller.yaml
Labels: approved, lgtm, size/XS

#29 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/eventing/pkg/apis/config/defaults.go
  vendor/knative.dev/eventing/pkg/apis/config/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/apis/eventing/register.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1alpha1/broker_defaults.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta1/broker_defaults.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta1/eventtype_types.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta1/eventtype_validation.go
  vendor/knative.dev/eventing/pkg/apis/flows/v1alpha1/parallel_defaults.go
  vendor/knative.dev/eventing/pkg/apis/flows/v1alpha1/sequence_defaults.go
  vendor/knative.dev/eventing/pkg/apis/flows/v1beta1/parallel_defaults.go
  vendor/knative.dev/eventing/pkg/apis/flows/v1beta1/sequence_defaults.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1alpha1/channel_defaults.go
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/metrics/exporter.go
  vendor/knative.dev/test-infra/scripts/README.md
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/knative.dev/test-infra/scripts/presubmit-tests.sh
Labels: approved, lgtm, size/L

#31 Drop use of deprecated filter API
  pkg/reconciler/controller.go
Labels: approved, cla: yes, lgtm, size/XS

#30 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/injection/clients/namespacedkube/informers/core/v1/secret/fake/fake.go
  vendor/knative.dev/pkg/injection/clients/namespacedkube/informers/core/v1/secret/secret.go
  vendor/knative.dev/pkg/injection/clients/namespacedkube/informers/factory/factory.go
  vendor/knative.dev/pkg/injection/clients/namespacedkube/informers/factory/fake/fake.go
  vendor/knative.dev/pkg/test/clients.go
  vendor/knative.dev/pkg/test/e2e_flags.go
  vendor/knative.dev/pkg/test/request.go
  vendor/knative.dev/pkg/test/spoof/spoof.go
  vendor/knative.dev/pkg/webhook/admission.go
  vendor/knative.dev/pkg/webhook/certificates/certificates.go
  vendor/knative.dev/pkg/webhook/certificates/controller.go
  vendor/knative.dev/pkg/webhook/configmaps/controller.go
  vendor/knative.dev/pkg/webhook/conversion.go
  vendor/knative.dev/pkg/webhook/psbinding/controller.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/conversion/controller.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/conversion/conversion.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/defaulting/controller.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/validation/controller.go
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/knative.dev/test-infra/scripts/release.sh
Labels: approved, cla: yes, lgtm, size/L

#34 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/eventing/cmd/mtbroker/filter/kodata/HEAD
  vendor/knative.dev/eventing/cmd/mtbroker/filter/kodata/LICENSE
  vendor/knative.dev/eventing/cmd/mtbroker/filter/kodata/VENDOR-LICENSE
  vendor/knative.dev/eventing/cmd/mtbroker/filter/kodata/refs
  vendor/knative.dev/eventing/cmd/mtbroker/ingress/kodata/HEAD
  vendor/knative.dev/eventing/cmd/mtbroker/ingress/kodata/LICENSE
  vendor/knative.dev/eventing/cmd/mtbroker/ingress/kodata/VENDOR-LICENSE
  vendor/knative.dev/eventing/cmd/mtbroker/ingress/kodata/refs
  vendor/knative.dev/eventing/config/brokers/mt-channel-broker/200-filter-clusterrole.yaml
  vendor/knative.dev/eventing/config/brokers/mt-channel-broker/200-filter-serviceaccount.yaml
  vendor/knative.dev/eventing/config/brokers/mt-channel-broker/200-ingress-clusterrole.yaml
  vendor/knative.dev/eventing/config/brokers/mt-channel-broker/200-ingress-serviceaccount.yaml
  vendor/knative.dev/eventing/config/brokers/mt-channel-broker/201-filter-clusterrolebinding.yaml
  vendor/knative.dev/eventing/config/brokers/mt-channel-broker/201-ingress-clusterrolebinding.yaml
  vendor/knative.dev/eventing/config/brokers/mt-channel-broker/500-broker-filter.yaml
  vendor/knative.dev/eventing/config/brokers/mt-channel-broker/500-broker-ingress.yaml
  vendor/knative.dev/eventing/config/brokers/mt-channel-broker/500-mt-broker-controller.yaml
  vendor/knative.dev/eventing/pkg/apis/duck/lifecycle_helper.go
  vendor/knative.dev/eventing/pkg/apis/eventing/register.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1alpha1/broker_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1alpha1/test_helper.go
  vendor/knative.dev/test-infra/scripts/README.md
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/knative.dev/test-infra/scripts/presubmit-tests.sh
Labels: approved, cla: yes, lgtm, size/L

#35 [master] Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/apis/condition_set.go
Labels: approved, cla: yes, lgtm, size/M

#36 [master] Auto-update dependencies
  Gopkg.lock
  vendor/github.com/google/go-cmp/cmp/cmpopts/equate.go
  vendor/github.com/google/go-cmp/cmp/compare.go
  vendor/github.com/google/go-cmp/cmp/export_panic.go
  vendor/github.com/google/go-cmp/cmp/export_unsafe.go
  vendor/github.com/google/go-cmp/cmp/internal/value/sort.go
  vendor/github.com/google/go-cmp/cmp/internal/value/zero.go
  vendor/github.com/google/go-cmp/cmp/options.go
  vendor/github.com/google/go-cmp/cmp/path.go
  vendor/github.com/google/go-cmp/cmp/report_compare.go
  vendor/github.com/google/go-cmp/cmp/report_reflect.go
  vendor/github.com/google/go-cmp/cmp/report_slices.go
  vendor/github.com/google/go-cmp/cmp/report_text.go
  vendor/golang.org/x/xerrors/LICENSE
  vendor/golang.org/x/xerrors/PATENTS
  vendor/golang.org/x/xerrors/adaptor.go
  vendor/golang.org/x/xerrors/doc.go
  vendor/golang.org/x/xerrors/errors.go
  vendor/golang.org/x/xerrors/fmt.go
  vendor/golang.org/x/xerrors/format.go
  vendor/golang.org/x/xerrors/frame.go
  vendor/golang.org/x/xerrors/internal/internal.go
  vendor/golang.org/x/xerrors/wrap.go
  vendor/knative.dev/eventing/pkg/apis/eventing/register.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1alpha1/eventtype_types.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1alpha1/eventtype_validation.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1alpha1/trigger_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta1/eventtype_types.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta1/eventtype_validation.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/apis/sources/register.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha1/apiserver_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha1/apiserver_types.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha1/ping_conversion.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha1/ping_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha1/ping_types.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/kncloudevents/utils.go
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/Gopkg.toml
  vendor/knative.dev/pkg/apis/duck/v1/source_types.go
  vendor/knative.dev/pkg/apis/duck/v1/zz_generated.deepcopy.go
Labels: approved, cla: yes, lgtm, size/XXL

#37 [master] Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/pkg/test/cmd/command.go
  vendor/knative.dev/pkg/testutils/clustermanager/e2e-tests/gke.go
Labels: approved, cla: yes, lgtm, size/M

#38 [master] Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/eventing/config/brokers/mt-channel-broker/400-config-br-defaults.yaml
  vendor/knative.dev/eventing/config/brokers/mt-channel-broker/hpa.yaml
  vendor/knative.dev/eventing/pkg/apis/configs/v1alpha1/configmappropagation_types.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1alpha1/trigger_types.go
  vendor/knative.dev/eventing/pkg/apis/sources/register.go
  vendor/knative.dev/eventing/pkg/kncloudevents/good_client.go
  vendor/knative.dev/eventing/pkg/kncloudevents/message_client.go
  vendor/knative.dev/pkg/kvstore/kvstore.go
  vendor/knative.dev/pkg/kvstore/kvstore_cm.go
  vendor/knative.dev/test-infra/scripts/library.sh
Labels: approved, cla: yes, lgtm, size/L

#41 [master] Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/eventing/config/200-channel-broker-binding.yaml
  vendor/knative.dev/eventing/config/200-channel-broker-clusterrole.yaml
  vendor/knative.dev/eventing/config/300-configmappropagation.yaml
  vendor/knative.dev/eventing/config/300-containersource.yaml
  vendor/knative.dev/eventing/config/400-config-br-default-channel.yaml
  vendor/knative.dev/eventing/config/400-config-br-defaults.yaml
  vendor/knative.dev/eventing/config/500-broker-controller.yaml
  vendor/knative.dev/eventing/config/brokers/channel-broker/200-channel-broker-clusterrole.yaml
  vendor/knative.dev/eventing/config/brokers/channel-broker/300-configmappropagation.yaml
  vendor/knative.dev/eventing/config/brokers/channel-broker/400-config-br-default-channel.yaml
  vendor/knative.dev/eventing/config/brokers/channel-broker/400-config-br-defaults.yaml
  vendor/knative.dev/eventing/config/brokers/channel-broker/500-broker-controller.yaml
  vendor/knative.dev/eventing/config/brokers/mt-channel-broker/400-config-br-default-channel.yaml
  vendor/knative.dev/eventing/pkg/apis/sources/register.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha2/container_defaults.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha2/container_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha2/container_types.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha2/container_validation.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha2/register.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha2/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/sources/v1alpha2/containersource.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/sources/v1alpha2/generated_expansion.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/sources/v1alpha2/sources_client.go
  vendor/knative.dev/eventing/pkg/client/informers/externalversions/generic.go
  vendor/knative.dev/eventing/pkg/client/informers/externalversions/sources/v1alpha2/containersource.go
  vendor/knative.dev/eventing/pkg/client/informers/externalversions/sources/v1alpha2/interface.go
  vendor/knative.dev/eventing/pkg/client/listers/sources/v1alpha2/containersource.go
  vendor/knative.dev/eventing/pkg/client/listers/sources/v1alpha2/expansion_generated.go
Labels: approved, cla: yes, lgtm, size/XL

#43 Replace util.GenerateFixedname with kmeta.ChildName
  Gopkg.lock
  pkg/reconciler/sample/resources/receive_adapter.go
  vendor/knative.dev/eventing/pkg/utils/context.go
  vendor/knative.dev/eventing/pkg/utils/secret.go
  vendor/knative.dev/eventing/pkg/utils/utils.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/L
