Repository knative-extensions/sample-source, pull requests merged in 2020-07, with the labels that each got.

#114 [master] Auto-update dependencies
  go.mod
  go.sum
  pkg/client/injection/reconciler/samples/v1alpha1/samplesource/controller.go
  pkg/client/injection/reconciler/samples/v1alpha1/samplesource/reconciler.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_controller.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/controller/options.go
  vendor/knative.dev/pkg/hack/update-deps.sh
  vendor/knative.dev/pkg/version/version.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#116 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/adapter/v2/cloudevents.go
  vendor/knative.dev/eventing/pkg/adapter/v2/main.go
  vendor/knative.dev/eventing/pkg/adapter/v2/main_message.go
  vendor/knative.dev/eventing/pkg/apis/duck/v1/subscribable_types.go
  vendor/knative.dev/eventing/pkg/apis/duck/v1/subscribable_types_conversion.go
  vendor/knative.dev/eventing/pkg/apis/duck/v1beta1/subscribable_types.go
  vendor/knative.dev/eventing/pkg/apis/duck/v1beta1/subscribable_types_conversion.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/broker_validation.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/trigger_types.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/trigger_validation.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta1/broker_validation.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta1/trigger_types.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta1/trigger_validation.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1/channel_validation.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1/subscription_validation.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1beta1/channel_conversion.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1beta1/in_memory_channel_conversion.go
  vendor/knative.dev/eventing/pkg/leaderelection/context.go
  vendor/knative.dev/eventing/pkg/leaderelection/leader_election.go
  vendor/knative.dev/pkg/hack/update-deps.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XL

#121 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/golang.org/x/tools/imports/forward.go
  vendor/golang.org/x/tools/internal/imports/fix.go
  vendor/golang.org/x/tools/internal/imports/imports.go
  vendor/golang.org/x/tools/internal/imports/sortimports.go
  vendor/google.golang.org/api/internal/settings.go
  vendor/google.golang.org/api/transport/grpc/dial.go
  vendor/google.golang.org/genproto/googleapis/devtools/cloudtrace/v2/trace.pb.go
  vendor/google.golang.org/genproto/googleapis/devtools/cloudtrace/v2/tracing.pb.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/broker_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/broker_lifecycle_mt.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta1/broker_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta1/broker_lifecycle_mt.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta1/eventtype_lifecycle.go
  vendor/knative.dev/pkg/apis/duck/ducktypes/ducktypes.go
  vendor/knative.dev/pkg/apis/duck/register.go
  vendor/knative.dev/pkg/apis/duck/v1/addressable_types.go
  vendor/knative.dev/pkg/apis/duck/v1/podspec_types.go
  vendor/knative.dev/pkg/apis/duck/v1/register.go
  vendor/knative.dev/pkg/apis/duck/v1/source_types.go
  vendor/knative.dev/pkg/apis/duck/v1/status_types.go
  vendor/knative.dev/pkg/apis/duck/v1_tests.go
  vendor/knative.dev/pkg/apis/duck/v1beta1/addressable_types.go
  vendor/knative.dev/pkg/apis/duck/v1beta1/register.go
  vendor/knative.dev/pkg/apis/duck/v1beta1/source_types.go
  vendor/knative.dev/pkg/apis/duck/v1beta1/status_types.go
  vendor/knative.dev/pkg/apis/duck/v1beta1_tests.go
  vendor/knative.dev/pkg/apis/duck/verify.go
  vendor/knative.dev/test-infra/scripts/e2e-tests.sh
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/knative.dev/test-infra/scripts/performance-tests.sh
  vendor/knative.dev/test-infra/scripts/presubmit-tests.sh
  vendor/knative.dev/test-infra/scripts/release.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XXL

#122 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/adapter/v2/cloudevents.go
  vendor/knative.dev/eventing/pkg/adapter/v2/config.go
  vendor/knative.dev/eventing/pkg/adapter/v2/main.go
  vendor/knative.dev/eventing/pkg/adapter/v2/main_message.go
  vendor/knative.dev/eventing/pkg/adapter/v2/util/crstatusevent/eventsstatus.go
  vendor/knative.dev/eventing/pkg/apis/flows/v1/parallel_types.go
  vendor/knative.dev/eventing/pkg/apis/flows/v1/sequence_types.go
  vendor/knative.dev/eventing/pkg/leaderelection/context.go
  vendor/knative.dev/eventing/pkg/leaderelection/leader_election.go
  vendor/knative.dev/pkg/apis/duck/v1_tests.go
  vendor/knative.dev/pkg/apis/duck/v1beta1/addressable_types.go
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/leaderelection/config.go
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XL

#124 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/cloud.google.com/go/container/apiv1/doc.go
  vendor/cloud.google.com/go/trace/apiv2/doc.go
  vendor/k8s.io/apimachinery/pkg/api/apitesting/fuzzer/fuzzer.go
  vendor/k8s.io/apimachinery/pkg/api/apitesting/fuzzer/valuefuzz.go
  vendor/knative.dev/eventing/pkg/apis/duck/v1/fuzzer.go
  vendor/knative.dev/eventing/pkg/apis/duck/v1beta1/delivery_conversion.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/fuzzer.go
  vendor/knative.dev/eventing/pkg/apis/flows/v1/fuzzer.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1/fuzzer.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1beta1/channel_conversion.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1beta1/in_memory_channel_conversion.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha1/sinkbinding_conversion.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha2/sinkbinding_conversion.go
  vendor/knative.dev/pkg/apis/testing/fuzzer/fuzzer.go
  vendor/knative.dev/pkg/hack/update-codegen.sh
  vendor/knative.dev/pkg/hash/bucketer.go
  vendor/knative.dev/pkg/leaderelection/context.go
  vendor/knative.dev/pkg/metrics/stackdriver_exporter.go
  vendor/knative.dev/pkg/network/network.go
  vendor/knative.dev/pkg/network/transports.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XL

#126 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/adapter/v2/config_watcher.go
  vendor/knative.dev/eventing/pkg/adapter/v2/main.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha1/apiserver_conversion.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha2/apiserver_conversion.go
  vendor/knative.dev/eventing/pkg/utils/cache/persisted_store.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/controller/two_lane_queue.go
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/leaderelection/context.go
  vendor/knative.dev/pkg/network/error_handler.go
  vendor/knative.dev/pkg/network/handlers/doc.go
  vendor/knative.dev/pkg/network/handlers/drain.go
  vendor/knative.dev/pkg/network/handlers/error.go
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/knative.dev/test-infra/scripts/e2e-tests.sh
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XXL

#127 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/contrib.go.opencensus.io/exporter/ocagent/go.mod
  vendor/contrib.go.opencensus.io/exporter/ocagent/go.sum
  vendor/contrib.go.opencensus.io/exporter/ocagent/ocagent.go
  vendor/contrib.go.opencensus.io/exporter/ocagent/options.go
  vendor/contrib.go.opencensus.io/exporter/ocagent/transform_stats_to_metrics.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/internal/BUILD.bazel
  vendor/github.com/grpc-ecosystem/grpc-gateway/internal/errors.pb.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/internal/errors.proto
  vendor/github.com/grpc-ecosystem/grpc-gateway/internal/stream_chunk.pb.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/internal/stream_chunk.proto
  vendor/github.com/grpc-ecosystem/grpc-gateway/runtime/BUILD.bazel
  vendor/github.com/grpc-ecosystem/grpc-gateway/runtime/context.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/runtime/errors.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/runtime/handler.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/runtime/marshal_httpbodyproto.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/runtime/marshaler.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/runtime/mux.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/runtime/proto_errors.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/runtime/query.go
  vendor/github.com/hashicorp/go-cleanhttp/LICENSE
  vendor/github.com/hashicorp/go-cleanhttp/README.md
  vendor/github.com/hashicorp/go-cleanhttp/cleanhttp.go
  vendor/github.com/hashicorp/go-cleanhttp/doc.go
  vendor/github.com/hashicorp/go-cleanhttp/go.mod
  vendor/github.com/hashicorp/go-cleanhttp/handlers.go
  vendor/github.com/hashicorp/go-retryablehttp/.gitignore
  vendor/github.com/hashicorp/go-retryablehttp/.travis.yml
  vendor/github.com/hashicorp/go-retryablehttp/LICENSE
  vendor/github.com/hashicorp/go-retryablehttp/Makefile
  vendor/github.com/hashicorp/go-retryablehttp/README.md
  vendor/github.com/hashicorp/go-retryablehttp/client.go
  vendor/github.com/hashicorp/go-retryablehttp/go.mod
  vendor/github.com/hashicorp/go-retryablehttp/go.sum
  vendor/github.com/hashicorp/go-retryablehttp/roundtripper.go
  vendor/knative.dev/eventing/pkg/kncloudevents/message_sender.go
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/metrics/opencensus_exporter.go
  vendor/knative.dev/pkg/network/handlers/drain.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XXL

#128 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/golang.org/x/sys/unix/syscall_linux.go
  vendor/golang.org/x/sys/unix/zsyscall_linux.go
  vendor/knative.dev/eventing/pkg/adapter/v2/util/crstatusevent/eventsstatus.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta1/trigger_conversion.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/controller/two_lane_queue.go
  vendor/knative.dev/pkg/hash/bucketer.go
  vendor/knative.dev/pkg/leaderelection/context.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#129 [master] Auto-update dependencies
  go.mod
  go.sum
  pkg/client/injection/reconciler/samples/v1alpha1/samplesource/reconciler.go
  pkg/client/injection/reconciler/samples/v1alpha1/samplesource/state.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/ignore.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/struct_filter.go
  vendor/github.com/google/go-cmp/cmp/report_reflect.go
  vendor/knative.dev/eventing/pkg/apis/eventing/register.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/packages.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler_stub.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_state.go
  vendor/knative.dev/pkg/injection/README.md
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XL

#130 Remove the reconciled event, it is not really useful
  pkg/reconciler/sample/samplesource.go
Labels: approved, cla: yes, lgtm, size/XS

#131 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/golang.org/x/sys/unix/mkerrors.sh
  vendor/golang.org/x/sys/unix/syscall_bsd.go
  vendor/golang.org/x/sys/unix/zerrors_openbsd_386.go
  vendor/golang.org/x/sys/unix/zerrors_openbsd_amd64.go
  vendor/golang.org/x/sys/unix/zerrors_openbsd_arm.go
  vendor/golang.org/x/sys/unix/zerrors_openbsd_arm64.go
  vendor/golang.org/x/time/rate/rate.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_state.go
  vendor/knative.dev/pkg/injection/README.md
  vendor/knative.dev/test-infra/scripts/presubmit-tests.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#132 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/network/transports.go
  vendor/knative.dev/test-infra/scripts/presubmit-tests.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#133 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/golang.org/x/sys/unix/zerrors_freebsd_386.go
  vendor/golang.org/x/sys/unix/zerrors_freebsd_amd64.go
  vendor/golang.org/x/sys/unix/zerrors_freebsd_arm.go
  vendor/golang.org/x/sys/unix/zerrors_freebsd_arm64.go
  vendor/knative.dev/pkg/ptr/ptr.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#135 Update CloudEvents SDK to v2.2.0
  go.mod
  go.sum
  vendor/github.com/cloudevents/sdk-go/v2/client/client.go
  vendor/github.com/cloudevents/sdk-go/v2/event/event_validation.go
  vendor/github.com/cloudevents/sdk-go/v2/protocol/http/result.go
  vendor/github.com/cloudevents/sdk-go/v2/protocol/http/write_request.go
  vendor/github.com/cloudevents/sdk-go/v2/protocol/result.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#136 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/golang.org/x/sys/unix/mkerrors.sh
  vendor/golang.org/x/sys/unix/zerrors_netbsd_386.go
  vendor/golang.org/x/sys/unix/zerrors_netbsd_amd64.go
  vendor/golang.org/x/sys/unix/zerrors_netbsd_arm.go
  vendor/golang.org/x/sys/unix/zerrors_netbsd_arm64.go
  vendor/knative.dev/eventing/pkg/adapter/v2/main.go
  vendor/knative.dev/eventing/pkg/adapter/v2/main_message.go
  vendor/knative.dev/eventing/pkg/apis/eventing/register.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha2/ping_conversion.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#137 [master] Auto-update dependencies
  go.mod
  go.sum
  pkg/client/injection/reconciler/samples/v1alpha1/samplesource/reconciler.go
  pkg/client/injection/reconciler/samples/v1alpha1/samplesource/state.go
  vendor/knative.dev/pkg/apis/contexts.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_state.go
  vendor/knative.dev/pkg/reconciler/reconcile_common.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#138 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/apis/volatile_time.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M
