Repository knative-extensions/sample-source, pull requests merged in 2023-01, with the labels that each got.

#450 Ran codegen with go1.19 & fix linter warnings
  pkg/apis/samples/v1alpha1/register_test.go
  pkg/client/clientset/versioned/fake/register.go
  pkg/client/clientset/versioned/scheme/register.go
Labels: lgtm, approved, size/XS

#448 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: lgtm, approved, size/XS, skip-review

#446 [main] Update community files
  OWNERS_ALIASES
Labels: lgtm, approved, size/M, skip-review

#451 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/sources/v1/apiserver_types.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: lgtm, approved, size/S
