Repository knative-extensions/sample-source, pull requests merged in 2023-04, with the labels that each got.

#465 [main] Update actions
  .github/workflows/knative-boilerplate.yaml
  .github/workflows/knative-donotsubmit.yaml
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-vulnerability.yaml
Labels: size/L, skip-review

#466 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#467 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#468 chore: migrate from k8s.gcr.io to registry.k8s.io
  config/config-observability.yaml
Labels: lgtm, approved, size/XS, needs-ok-to-test

#470 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review
