Repository knative-extensions/sample-source, pull requests merged in 2024-05, with the labels that each got.

#588 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#590 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/sources/v1/container_lifecycle.go
  vendor/modules.txt
Labels: lgtm, approved, size/M

#592 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review

#593 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/apis/duck/v1/auth_types.go
  vendor/knative.dev/pkg/apis/duck/v1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: lgtm, approved, size/S

#594 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/eventingtls/trust_bundle.go
  vendor/modules.txt
Labels: lgtm, approved, size/M

#597 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/crossnamespace/validation.go
  vendor/modules.txt
Labels: lgtm, approved, size/M

#595 fix: pass application context to adapter setup
  cmd/receive_adapter/main.go
Labels: lgtm, approved, size/XS

#601 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/reconciler/configstore.go
  vendor/modules.txt
Labels: lgtm, approved, size/M

#602 [main] Update actions
  .github/workflows/knative-go-test.yaml
Labels: size/XS, skip-review

#603 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/google.golang.org/genproto/googleapis/rpc/status/status.pb.go
  vendor/google.golang.org/grpc/CONTRIBUTING.md
  vendor/google.golang.org/grpc/MAINTAINERS.md
  vendor/google.golang.org/grpc/Makefile
  vendor/google.golang.org/grpc/binarylog/grpc_binarylog_v1/binarylog.pb.go
  vendor/google.golang.org/grpc/clientconn.go
  vendor/google.golang.org/grpc/codegen.sh
  vendor/google.golang.org/grpc/codes/codes.go
  vendor/google.golang.org/grpc/credentials/credentials.go
  vendor/google.golang.org/grpc/dialoptions.go
  vendor/google.golang.org/grpc/health/grpc_health_v1/health.pb.go
  vendor/google.golang.org/grpc/health/grpc_health_v1/health_grpc.pb.go
  vendor/google.golang.org/grpc/internal/balancer/gracefulswitch/config.go
  vendor/google.golang.org/grpc/internal/balancer/gracefulswitch/gracefulswitch.go
  vendor/google.golang.org/grpc/internal/binarylog/method_logger.go
  vendor/google.golang.org/grpc/internal/envconfig/envconfig.go
  vendor/google.golang.org/grpc/internal/grpcutil/compressor.go
  vendor/google.golang.org/grpc/internal/resolver/dns/dns_resolver.go
  vendor/google.golang.org/grpc/internal/resolver/dns/internal/internal.go
  vendor/google.golang.org/grpc/internal/transport/controlbuf.go
  vendor/google.golang.org/grpc/internal/transport/http2_client.go
  vendor/google.golang.org/grpc/internal/transport/http2_server.go
  vendor/google.golang.org/grpc/internal/transport/transport.go
  vendor/google.golang.org/grpc/metadata/metadata.go
  vendor/google.golang.org/grpc/peer/peer.go
  vendor/google.golang.org/grpc/picker_wrapper.go
  vendor/google.golang.org/grpc/pickfirst.go
  vendor/google.golang.org/grpc/regenerate.sh
  vendor/google.golang.org/grpc/resolver/dns/dns_resolver.go
  vendor/google.golang.org/grpc/rpc_util.go
  vendor/google.golang.org/grpc/server.go
  vendor/google.golang.org/grpc/service_config.go
  vendor/google.golang.org/grpc/stats/stats.go
  vendor/google.golang.org/grpc/stream.go
  vendor/google.golang.org/grpc/stream_interfaces.go
  vendor/google.golang.org/grpc/version.go
  vendor/google.golang.org/grpc/vet.sh
  vendor/knative.dev/eventing/pkg/apis/eventing/register.go
  vendor/knative.dev/eventing/pkg/crossnamespace/validation.go
  vendor/knative.dev/eventing/pkg/eventingtls/trust_bundle.go
  vendor/modules.txt
Labels: lgtm, approved, size/XL

#604 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/github.com/stretchr/testify/assert/assertion_compare.go
  vendor/github.com/stretchr/testify/assert/assertion_compare_can_convert.go
  vendor/github.com/stretchr/testify/assert/assertion_compare_legacy.go
  vendor/github.com/stretchr/testify/assert/assertion_format.go
  vendor/github.com/stretchr/testify/assert/assertion_forward.go
  vendor/github.com/stretchr/testify/assert/assertions.go
  vendor/github.com/stretchr/testify/assert/http_assertions.go
  vendor/github.com/stretchr/testify/require/require.go
  vendor/github.com/stretchr/testify/require/require_forward.go
  vendor/modules.txt
Labels: lgtm, approved, size/XL

#606 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/network/network.go
  vendor/modules.txt
Labels: lgtm, approved, size/S
